class NewsPrompts():
    INPUT_VALIDATION_SYSTEM = """ You are a meticulous reviewer of words and phrases. """

    @staticmethod
    def input_validation_user(query: str) -> str:
        return f""" Topic: {query}
                Determine whether the query is inappropriate or contains harmful requests.

                Only respond with True if it does or False if it doesnt

                """
    
    SEARCH_QUERY_OPTIMIZER = """ Your are a news search engine expert. """

    @staticmethod
    def user_search_query_optimizer(query: str) -> str:
        return f"""
                Query: {query}

                Determine if the query is sufficient for a search engine to return valuable articles pertaining to the query

                If the query is sufficient respond with the query.
                If the query is not sufficient respond with an enhanced query generated by you.
                """
    
    DOCUMENT_SUMMARIZER = """ You are an expert at summarizing documents. """

    @staticmethod
    def user_document_summarizer(article) -> str:
        return f"""
                Content: {article}

                Number and summarize the most exciting news clippings from the content.
                """